Repository Shift3/standards-and-practices, pull requests merged in 2020-09, with the labels that each got.

#203 feat(pr-template): add helpful sections to pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#209 feature(react-readme): add content to react readme
  best-practices/client-side/framework/react/README.md
Labels: enhancement

#207 feature(react-native): Working react native without expo setup
  best-practices/development-tools/continuous-integration/react_native.yml
Labels: discussion, enhancement

#205 feature(git-hooks): Git Hooks should be referenced
  standards/git-commands.md
Labels: enhancement

#211 fix(awesome-whitelist): Whitelist all Shift3 resources from awesome_bot
  .circleci/config.yml
Labels: bug

#214 feature(semver-example): add example to better explain semver
  standards/assets/qa-process/semver.png
  standards/code-versioning.md
Labels: enhancement

#216 Docker instructions for installing MSSQL
  best-practices/database/README.md
Labels: enhancement
