Repository Shift3/standards-and-practices, pull requests merged in 2020-07, with the labels that each got.

#185 Add a ts version of button
  best-practices/native/react-native/common-components/button.js
  best-practices/native/react-native/common-components/buttons/button.js
  best-practices/native/react-native/common-components/buttons/button.tsx
Labels: Maintanence, enhancement

#179 feature(setup-databases): Setup mysql for ubuntu
  best-practices/database/README.md
Labels: discussion, enhancement

#177 feat(README): Add basic links to visual studio tooling and FM
  README.md
Labels: enhancement

#175 fix(client-side-links): Deprecate client links
  best-practices/client-side/README.md
Labels: discussion, enhancement

#163 feat(awesome-bot): check all available links
  .circleci/config.yml
Labels: enhancement

#173 refactor(frameworks): Split out languages from frameworks
  best-practices/server-side/framework/README.md
Labels: discussion

#169 fix(standards): Remove or replace broken links
  standards/code-reviews.md
  standards/contributing.md
  standards/readme-guidelines.md
Labels: bug

#176 feat(react-with-server): Reactjs with server integration
  best-practices/development-tools/continuous-integration/react_with_python_config.yml
Labels: discussion, enhancement

#189 WIP: Fix url redirects
  .circleci/config.yml
  best-practices/native/react-native/expo/certificates/README.md
  best-practices/native/react-native/expo/upgrade/README.md
  best-practices/server-side/framework/php/laravel/README.md
  standards/code-versioning.md
Labels: bug

#188 Link Vue back into list of client frameworks
  best-practices/client-side/framework/README.md
  best-practices/client-side/framework/vue/README.md
Labels: bug, discussion, enhancement

#191 feature(presentation): Presentation link and timeframe
  README.md
Labels: enhancement
