Repository Shift3/standards-and-practices, pull requests merged in 2021-03, with the labels that each got.

#252 refactor(re-branding): Re-brand Shift3 to Bitwise
  README.md
  best-practices/development-tools/accessibility/README.md
  best-practices/native/react-native/README.md
  best-practices/native/react-native/rn-by-example/README.md
  best-practices/native/react-native/startup/native-code.md
  best-practices/native/xamarin/README.md
  best-practices/server-side/security/README.md
  presentations/README.md
  standards/README.md
  standards/acceptance-testing.md
  standards/code-reviews.md
  standards/code-versioning.md
  standards/commits.md
  standards/contributing.md
  standards/git-commands.md
  standards/project-setup.md
  standards/qa-process.md
  standards/readme-guidelines.md
  workshops/README.md
Labels: Maintanence

#253 fix(spelling): Quick overview of our spelling
  best-practices/development-tools/accessibility/README.md
  best-practices/development-tools/accessibility/WCAG-testing.md
  best-practices/native/react-native/deployment/android/README.md
  best-practices/native/react-native/deployment/ios/README.md
  best-practices/native/react-native/expo/upgrade/README.md
Labels: bug

#255 fix(meeting-contact): More accurate Bitwise Meetings
  README.md
Labels: Maintanence

#247 doc(azure-devo-ops): Add a documentation for deployment using azure DevOps
  best-practices/development-tools/azure/devops/README.md
  best-practices/development-tools/azure/devops/continuous-integration/azure-app-functions-continuous-integration.md
  best-practices/development-tools/azure/devops/continuous-integration/azure-pipelines-azure-app-functions-ci.yml
  best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/aws-elastic-beanstalk-deployment.md
  best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/azure-pipelines-aws-eb-cd.yml
  best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/azure-pipelines-aws-eb-docker-cd.yml
  best-practices/development-tools/azure/devops/deployment/azure-app-functions/azure-app-functions-deployment.md
  best-practices/development-tools/azure/devops/deployment/azure-app-functions/azure-pipelines-azure-app-functions-cd.yml
Labels: Good First Contribution, help wanted

#256 feature(security): Client security docs
  best-practices/client-side/README.md
  best-practices/client-side/security/README.md
Labels: discussion, enhancement
