Repository Shift3/standards-and-practices, pull requests merged in 2021-09, with the labels that each got.

#281 docs(commits): update with commit messages information
  standards/commits.md
Labels: enhancement, discussion

#290 Update Epic Issue Template
  .github/ISSUE_TEMPLATE/epic-issue-template.md
Labels: enhancement

#291 feat(ios-deploy): iOS Specific Instructions on Deployments
  best-practices/native/react-native/deployment/ios/README.md
Labels: bug, enhancement
